# Generated by Django 4.0 on 2022-03-17 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_alter_event_eventname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='startDate',
            field=models.DateTimeField(default='', null=True),
        ),
    ]
